// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Seguridad.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426181217_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.AsignacionEquipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Equipamiento")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("equipamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fechaEntrega")
                        .HasColumnType("date");

                    b.Property<int>("identidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Equipamiento");

                    b.HasIndex("Id_Identidad");

                    b.ToTable("AsignacionEquipamientos");
                });

            modelBuilder.Entity("Entities.Equipamiento", b =>
                {
                    b.Property<int>("Id_Equipamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Equipamiento"));

                    b.Property<string>("CodigoEquipamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Equipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Equipamiento");

                    b.ToTable("Equipamiento");
                });

            modelBuilder.Entity("Entities.IdentidadAcceso", b =>
                {
                    b.Property<int>("Id_Identidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Identidad"));

                    b.Property<string>("CodigoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Identidad");

                    b.ToTable("IdentidadAcceso");
                });

            modelBuilder.Entity("Entities.AsignacionEquipamiento", b =>
                {
                    b.HasOne("Entities.Equipamiento", "equipamiento")
                        .WithMany("AsignacionEquipamietnos")
                        .HasForeignKey("Id_Equipamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.IdentidadAcceso", "identidad")
                        .WithMany("asignacionEquipamiento")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipamiento");

                    b.Navigation("identidad");
                });

            modelBuilder.Entity("Entities.Equipamiento", b =>
                {
                    b.Navigation("AsignacionEquipamietnos");
                });

            modelBuilder.Entity("Entities.IdentidadAcceso", b =>
                {
                    b.Navigation("asignacionEquipamiento");
                });
#pragma warning restore 612, 618
        }
    }
}
