// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Seguridad.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entities.AccesoRegistros", b =>
                {
                    b.Property<int>("id_Registros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_Registros"));

                    b.Property<string>("CodigoArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DispositivoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<DateTime>("HorarioRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Dispositivo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdentidadId")
                        .HasColumnType("integer");

                    b.HasKey("id_Registros");

                    b.HasIndex("Id_Dispositivo");

                    b.HasIndex("Id_Identidad");

                    b.ToTable("AccesoRegistros");
                });

            modelBuilder.Entity("Entities.AsignacionEquipamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Equipamiento")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("equipamientoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fechaEntrega")
                        .HasColumnType("date");

                    b.Property<int>("identidadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Equipamiento");

                    b.HasIndex("Id_Identidad");

                    b.ToTable("AsignacionEquipamientos");
                });

            modelBuilder.Entity("Entities.DatosBiometricos", b =>
                {
                    b.Property<int>("Id_DatosBio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_DatosBio"));

                    b.Property<string>("CodigoDato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DatoHuella")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdentidadId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoDatoBiometrico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_DatosBio");

                    b.HasIndex("Id_Identidad");

                    b.ToTable("DatosBiometricos");
                });

            modelBuilder.Entity("Entities.Dispositivo", b =>
                {
                    b.Property<int>("Id_Dispositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Dispositivo"));

                    b.Property<string>("CodigoArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreDispositivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Dispositivo");

                    b.ToTable("Dispositivo");
                });

            modelBuilder.Entity("Entities.Equipamiento", b =>
                {
                    b.Property<int>("Id_Equipamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Equipamiento"));

                    b.Property<string>("CodigoEquipamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Equipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Equipamiento");

                    b.ToTable("Equipamiento");
                });

            modelBuilder.Entity("Entities.Horario", b =>
                {
                    b.Property<int>("Id_Horario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Horario"));

                    b.Property<string>("CodigoHorario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraFin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Horario");

                    b.ToTable("Horario");
                });

            modelBuilder.Entity("Entities.IdentidadAcceso", b =>
                {
                    b.Property<int>("Id_Identidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Identidad"));

                    b.Property<string>("CodigoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Identidad");

                    b.ToTable("IdentidadAcceso");
                });

            modelBuilder.Entity("Entities.Reporte", b =>
                {
                    b.Property<int>("Id_Reporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Reporte"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("IdentidadId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoReporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("codigoReporte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Reporte");

                    b.HasIndex("Id_Identidad");

                    b.ToTable("Reporte");
                });

            modelBuilder.Entity("Entities.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("CodigoRol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Rol");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("Entities.RolHorario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HoraioId")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Horario")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<string>("codigoArea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Horario");

                    b.HasIndex("Id_Rol");

                    b.ToTable("RolHorario");
                });

            modelBuilder.Entity("Entities.RolIdentidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_Identidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int>("IdentidadId")
                        .HasColumnType("integer");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id_Identidad");

                    b.HasIndex("Id_Rol");

                    b.ToTable("RolIdentidad");
                });

            modelBuilder.Entity("Entities.AccesoRegistros", b =>
                {
                    b.HasOne("Entities.Dispositivo", "dispositivo")
                        .WithMany("accesoRegistro")
                        .HasForeignKey("Id_Dispositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.IdentidadAcceso", "identidad")
                        .WithMany("accesosRegistro")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dispositivo");

                    b.Navigation("identidad");
                });

            modelBuilder.Entity("Entities.AsignacionEquipamiento", b =>
                {
                    b.HasOne("Entities.Equipamiento", "equipamiento")
                        .WithMany("AsignacionEquipamietnos")
                        .HasForeignKey("Id_Equipamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.IdentidadAcceso", "identidad")
                        .WithMany("asignacionEquipamiento")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("equipamiento");

                    b.Navigation("identidad");
                });

            modelBuilder.Entity("Entities.DatosBiometricos", b =>
                {
                    b.HasOne("Entities.IdentidadAcceso", "identiidad")
                        .WithMany("DatosBio")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("identiidad");
                });

            modelBuilder.Entity("Entities.Reporte", b =>
                {
                    b.HasOne("Entities.IdentidadAcceso", "identidadd")
                        .WithMany("reportes")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("identidadd");
                });

            modelBuilder.Entity("Entities.RolHorario", b =>
                {
                    b.HasOne("Entities.Horario", "horario")
                        .WithMany("rolHorarios")
                        .HasForeignKey("Id_Horario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Rol", "rol")
                        .WithMany("rolHorario")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("horario");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("Entities.RolIdentidad", b =>
                {
                    b.HasOne("Entities.IdentidadAcceso", "identidad")
                        .WithMany("rolPersona")
                        .HasForeignKey("Id_Identidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Rol", "rol")
                        .WithMany("rolIdentidad")
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("identidad");

                    b.Navigation("rol");
                });

            modelBuilder.Entity("Entities.Dispositivo", b =>
                {
                    b.Navigation("accesoRegistro");
                });

            modelBuilder.Entity("Entities.Equipamiento", b =>
                {
                    b.Navigation("AsignacionEquipamietnos");
                });

            modelBuilder.Entity("Entities.Horario", b =>
                {
                    b.Navigation("rolHorarios");
                });

            modelBuilder.Entity("Entities.IdentidadAcceso", b =>
                {
                    b.Navigation("DatosBio");

                    b.Navigation("accesosRegistro");

                    b.Navigation("asignacionEquipamiento");

                    b.Navigation("reportes");

                    b.Navigation("rolPersona");
                });

            modelBuilder.Entity("Entities.Rol", b =>
                {
                    b.Navigation("rolHorario");

                    b.Navigation("rolIdentidad");
                });
#pragma warning restore 612, 618
        }
    }
}
